services:
  hashcraft:
    image: hashcraft
    container_name: hashcraft
    restart: always
    ports:
      - 27:27
    networks:
      hashcraft-network:
        ipv4_address: 172.20.128.3

networks:
  hashcraft-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
